version: '3'

services:
  node-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm start
    env_file:
      - .env
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - /path/to/your/postgres/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
